// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBranch = "branch"

// Branch mapped from table <branch>
type Branch struct {
	ID   int16  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Branch's table name
func (*Branch) TableName() string {
	return TableNameBranch
}
