// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCashier = "cashiers"

// Cashier mapped from table <cashiers>
type Cashiers struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	Passcode  string    `gorm:"column:passcode" json:"passcode"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	DtmUpd    time.Time `gorm:"column:dtm_upd" json:"dtm_upd"`
}

// TableName Cashier's table name
func (*Cashiers) TableName() string {
	return TableNameCashier
}
