// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID           int16  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SalesmanID   int16  `gorm:"column:salesman_id;not null" json:"salesman_id"`
	CustomerName string `gorm:"column:customer_name;not null" json:"customer_name"`
	OutletName   string `gorm:"column:outlet_name;not null" json:"outlet_name"`
	Type         string `gorm:"column:type;not null" json:"type"`
	Address      string `gorm:"column:address;not null" json:"address"`
	SubDistrict  string `gorm:"column:sub_district;not null" json:"sub_district"`
	District     string `gorm:"column:district;not null" json:"district"`
	Province     string `gorm:"column:province;not null" json:"province"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
