// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDiscount = "discounts"

// Discount mapped from table <discounts>
type Discount struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Qty             int64     `gorm:"column:qty" json:"qty"`
	Type            string    `gorm:"column:type" json:"type"`
	Result          int64     `gorm:"column:result" json:"result"`
	ExpiredAt       int64     `gorm:"column:expired_at" json:"expired_at"`
	ExpiredAtFormat string    `gorm:"column:expired_at_format" json:"expired_at_format"`
	StringFormat    string    `gorm:"column:string_format" json:"string_format"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Discount's table name
func (*Discount) TableName() string {
	return TableNameDiscount
}
