// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CashierID      int64     `gorm:"column:cashier_id" json:"cashier_id"`
	PaymentTypesID int64     `gorm:"column:payment_types_id" json:"payment_types_id"`
	TotalPrice     int64     `gorm:"column:total_price" json:"total_price"`
	TotalPaid      int64     `gorm:"column:total_paid" json:"total_paid"`
	TotalReturn    int64     `gorm:"column:total_return" json:"total_return"`
	ReceiptID      string    `gorm:"column:receipt_id" json:"receipt_id"`
	IsDownload     int64     `gorm:"column:is_download" json:"is_download"`
	ProductID      string    `gorm:"column:product_id" json:"product_id"`
	Quantities     string    `gorm:"column:quantities" json:"quantities"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
