// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string    `gorm:"column:name" json:"name"`
	Type          string    `gorm:"column:type" json:"type"`
	PaymentTypeID int64     `gorm:"column:payment_type_id" json:"payment_type_id"`
	Logo          string    `gorm:"column:logo" json:"logo"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
