// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductBranch = "product_branch"

// ProductBranch mapped from table <product_branch>
type ProductBranch struct {
	BranchID  int16 `gorm:"column:branch_id;primaryKey" json:"branch_id"`
	ProductID int16 `gorm:"column:product_id;primaryKey" json:"product_id"`
}

// TableName ProductBranch's table name
func (*ProductBranch) TableName() string {
	return TableNameProductBranch
}
