// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSalesman = "salesman"

// Salesman mapped from table <salesman>
type Salesman struct {
	ID        int16     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BranchID  int16     `gorm:"column:branch_id;not null" json:"branch_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName Salesman's table name
func (*Salesman) TableName() string {
	return TableNameSalesman
}
