// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransactionSale = "transaction_sale"

// TransactionSale mapped from table <transaction_sale>
type TransactionSale struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SalesmanID      int16     `gorm:"column:salesman_id;not null" json:"salesman_id"`
	CustomerID      int32     `gorm:"column:customer_id;not null" json:"customer_id"`
	TransactionDate time.Time `gorm:"column:transaction_date;not null;default:now()" json:"transaction_date"`
	Invoice         string    `gorm:"column:invoice" json:"invoice"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName TransactionSale's table name
func (*TransactionSale) TableName() string {
	return TableNameTransactionSale
}
