// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransactionSaleDetail = "transaction_sale_detail"

// TransactionSaleDetail mapped from table <transaction_sale_detail>
type TransactionSaleDetail struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransactionID int64     `gorm:"column:transaction_id;not null" json:"transaction_id"`
	ProductID     int16     `gorm:"column:product_id;not null" json:"product_id"`
	Price         int32     `gorm:"column:price;not null" json:"price"`
	Qty           int32     `gorm:"column:qty;not null" json:"qty"`
	Discount      int32     `gorm:"column:discount;not null" json:"discount"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName TransactionSaleDetail's table name
func (*TransactionSaleDetail) TableName() string {
	return TableNameTransactionSaleDetail
}
